version: '3.7'
services:
  database:
    image: 'mysql:latest'
    container_name: 'mysql'
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=iaheroku
      - MYSQL_USER=test
      - MYSQL_PASSWORD=secret
volumes:
  db_data: